@startuml Database

entity User {
  * id
  __
  * name
  * phone
  * email
  * status
  * password
  * role_id
}

entity Role {
  * id
  __
  * name
}

entity Member {
  * id
  __
  * name
  * phone
  * plat_number
  * type_member_id
}

entity TypeVehicle {
  * id
  __
  * type
}

entity ParkingFee {
  * id
  __
  * price
  * time_period
  * type_vehicle_id
}

entity Transaction {
  * id
  __
  * capture_vehicle
  * transaction_number
  * login_time
  time_out
  plat_number
  price
  type_vehicle_id
  user_id
  member_id
}

entity Expense {
  * id
  __
  * description
  * amount
  * user_id
}

entity Mutation {
  * id
  __
  * type
  * amount
  transaction_id
  expense_id
  topup_id
}

entity TopUp {
  * id
  __
  * amount
  * exp_date
  * member_id
  * user_id
}

entity TypeMember {
  * id
  __
  * type
  * price
}

Transaction ||--|{ Member
Transaction ||--|{ TypeVehicle
Transaction ||--|| Mutation
Transaction ||--|{ User
TypeVehicle }|--|| ParkingFee
Expense ||--|| Mutation
TopUp ||--|| Mutation
User ||--|{ Role
User }|--|| TopUp
User }|--|| Expense
Member }|--|| TopUp
Member ||--|| TypeMember